### PR TITLE
Add support for DCH-S160

### PR DESCRIPTION
**Pull request by postlund**
This is WIP for now as I don't have a unit. What I need is the output from:

    python3 custom_components/dlink_hnap/dlink.py <ip> <pin> water_detected

@ Molodax Can you help out?

### CODE REVIEW

**Comment by Molodax** [comment]
The water sensor doesn't work, while motion sensors are ok:

2020-07-25 17:03:33 ERROR (MainThread) [custom_components.dlink_hnap.dlink] Got an error, resetting private key
2020-07-25 17:03:33 ERROR (MainThread) [custom_components.dlink_hnap.binary_sensor] failed to update motion sensor
Traceback (most recent call last):
  File "/config/custom_components/dlink_hnap/dlink.py", line 116, in call
    result = await self.soap().call(method, **kwargs)
  File "/config/custom_components/dlink_hnap/dlink.py", line 253, in call
    resp = await self.session.post(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 582, in _request
    break
  File "/usr/local/lib/python3.8/site-packages/aiohttp/helpers.py", line 586, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/dlink_hnap/binary_sensor.py", line 88, in async_update
    last_trigger = await self._motion_sensor.latest_trigger()
  File "/config/custom_components/dlink_hnap/dlink.py", line 169, in latest_trigger
    await self._cache_soap_actions()
  File "/config/custom_components/dlink_hnap/dlink.py", line 192, in _cache_soap_actions
    resp = await self.client.soap_actions(self.module_id)
  File "/config/custom_components/dlink_hnap/dlink.py", line 106, in soap_actions
    return await self.call("GetModuleSOAPActions", ModuleID=module_id)
  File "/config/custom_components/dlink_hnap/dlink.py", line 112, in call
    await self.login()
  File "/config/custom_components/dlink_hnap/dlink.py", line 57, in login
    resp = await self.call(
  File "/config/custom_components/dlink_hnap/dlink.py", line 120, in call
    self._bad_response()
  File "/config/custom_components/dlink_hnap/dlink.py", line 126, in _bad_response
    raise Exception("got error response from device")
Exception: got error response from device

**Comment by postlund** [comment]
If you port scan the water sensor, what ports rate open?

**Comment by Molodax** [comment]
sorry, I provided a wrong host ip, but after the update there is still:

2020-07-25 17:23:20 ERROR (MainThread) [custom_components.dlink_hnap.dlink] Got an error, resetting private key
2020-07-25 17:23:20 ERROR (MainThread) [custom_components.dlink_hnap.binary_sensor] failed to update motion sensor
Traceback (most recent call last):
  File "/config/custom_components/dlink_hnap/dlink.py", line 116, in call
    result = await self.soap().call(method, **kwargs)
  File "/config/custom_components/dlink_hnap/dlink.py", line 253, in call
    resp = await self.session.post(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 582, in _request
    break
  File "/usr/local/lib/python3.8/site-packages/aiohttp/helpers.py", line 586, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/dlink_hnap/binary_sensor.py", line 88, in async_update
    last_trigger = await self._motion_sensor.latest_trigger()
  File "/config/custom_components/dlink_hnap/dlink.py", line 169, in latest_trigger
    await self._cache_soap_actions()
  File "/config/custom_components/dlink_hnap/dlink.py", line 192, in _cache_soap_actions
    resp = await self.client.soap_actions(self.module_id)
  File "/config/custom_components/dlink_hnap/dlink.py", line 106, in soap_actions
    return await self.call("GetModuleSOAPActions", ModuleID=module_id)
  File "/config/custom_components/dlink_hnap/dlink.py", line 112, in call
    await self.login()
  File "/config/custom_components/dlink_hnap/dlink.py", line 57, in login
    resp = await self.call(
  File "/config/custom_components/dlink_hnap/dlink.py", line 120, in call
    self._bad_response()
  File "/config/custom_components/dlink_hnap/dlink.py", line 126, in _bad_response
    raise Exception("got error response from device")
Exception: got error response from device
2020-07-25 17:23:35 ERROR (MainThread) [custom_components.dlink_hnap.dlink] Got an error, resetting private key
2020-07-25 17:23:35 ERROR (MainThread) [custom_components.dlink_hnap.binary_sensor] failed to update motion sensor
Traceback (most recent call last):
  File "/config/custom_components/dlink_hnap/dlink.py", line 116, in call
    result = await self.soap().call(method, **kwargs)
  File "/config/custom_components/dlink_hnap/dlink.py", line 253, in call
    resp = await self.session.post(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 582, in _request
    break
  File "/usr/local/lib/python3.8/site-packages/aiohttp/helpers.py", line 586, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/dlink_hnap/binary_sensor.py", line 88, in async_update
    last_trigger = await self._motion_sensor.latest_trigger()
  File "/config/custom_components/dlink_hnap/dlink.py", line 169, in latest_trigger
    await self._cache_soap_actions()
  File "/config/custom_components/dlink_hnap/dlink.py", line 192, in _cache_soap_actions
    resp = await self.client.soap_actions(self.module_id)
  File "/config/custom_components/dlink_hnap/dlink.py", line 106, in soap_actions
    return await self.call("GetModuleSOAPActions", ModuleID=module_id)
  File "/config/custom_components/dlink_hnap/dlink.py", line 112, in call
    await self.login()
  File "/config/custom_components/dlink_hnap/dlink.py", line 57, in login
    resp = await self.call(
  File "/config/custom_components/dlink_hnap/dlink.py", line 120, in call
    self._bad_response()
  File "/config/custom_components/dlink_hnap/dlink.py", line 126, in _bad_response
    raise Exception("got error response from device")
Exception: got error response from device

**Comment by Molodax** [comment]
> If you port scan the water sensor, what ports rate open?

not sure I understood your question :/

**Comment by postlund** [comment]
@Molodax It's just a plain HTTP protocol on port 80, so you can point your web browser to the IP address. Does that work with the motion sensor? Water sensor? In case they changed port from 80, a port scan (e.g. with nmap) would give some hints.

**Comment by Molodax** [comment]
> @Molodax It's just a plain HTTP protocol on port 80, so you can point your web browser to the IP address. Does that work with the motion sensor? Water sensor? In case they changed port from 80, a port scan (e.g. with nmap) would give some hints.

Disregard my previous logs, the error with the water sensor was due to wrong host IP. The component works with both motion and water 👍 sorry for the confusion.

**Comment by postlund** [comment]
Oh, does it work out of the box?

**Comment by Molodax** [comment]
> Oh, does it work out of the box?

yes, no additional actions from my side. just using PIN from sticker as a password in the same way as with motion sensor.

**Comment by postlund** [comment]
Alright, yes, it probably works in some sense. The same attribute probably change for both sensor types. But there's no check if water was detected or not now. So what we are likely seeing is the state when it either got wet OR dried up + timeout interval (35s). I would like to add the check if water was detected or not and mainly base the state on that. Hopefully the command above gives us that. Can you still run that with correct IP and report back?

**Comment by Molodax** [comment]
> Alright, yes, it probably works in some sense. The same attribute probably change for both sensor types. But there's no check if water was detected or not now. So what we are likely seeing is the state when it either got wet OR dried up + timeout interval (35s). I would like to add the check if water was detected or not and mainly base the state on that. Hopefully the command above gives us that. Can you still run that with correct IP and report back?

If you could be more explicit which command to run, I'll definitely try and report back

**Comment by postlund** [comment]
> If you could be more explicit which command to run, I'll definitely try and report back

Yeah, it's this one:

    python3 custom_components/dlink_hnap/dlink.py <ip> <pin> water_detected

You can't run it via Home Assistant though, it must be done via terminal. You either clone the repo to some computer and run it or do it from your current home assistant installation (via ssh for instance). Not sure how you installed he Assistant?

**Comment by Molodax** [comment]
> Not sure how you installed he Assistant?

I'm running Hassio or whatever it's called now, so it will not be possible via ssh either. I can find my old rpi3 but it'll take some time

**Comment by ebear5** [comment]
I'm running Hass in docker.  But as a noob you'll have to guide me slowly beyond that.

if I ssh to the docker directory and run the command i get: 

Traceback (most recent call last):
  File "dlink.py", line 10, in <module>
    import aiohttp
ImportError: No module named 'aiohttp'

**Comment by Molodax** [comment]
> python3 custom_components/dlink_hnap/dlink.py <ip> <pin> water_detected

I've gotten the following:

$ python3 dlink.py 192.168.149.151 534691 water_detected
DEBUG:asyncio:Using selector: EpollSelector
INFO:__main__:Logging into device
DEBUG:__main__:Challenge: Gk45HAjLP5qrm8VTQcAI, Public key: IKAueQpY2s6kHFMp9yiR                                     , Cookie: j5qbsknX4i
DEBUG:__main__:Private key: 4C9646FD5ABCC5C4843BAF094728DB85
DEBUG:__main__:Generated new token for Login: 11C56C3C6A95FD1CD59DB77C5C227B5E (                                     time: 1595800827)
DEBUG:__main__:Generated new token for GetDeviceSettings: C0A78E34787FFE2EA82293                                     E844B68F52 (time: 1595800828)
DEBUG:__main__:Generated new token for GetModuleSOAPActions: 0163E838767E4DDEC3A                                     F786375B5ED92 (time: 1595800828)
DEBUG:__main__:Generated new token for GetWaterDetectorState: F2AECBCD5EC86828B1                                     4B01527FDEA5B4 (time: 1595800828)
Water detectes: OrderedDict([('@xmlns', 'http://purenetworks.com/HNAP1/'), ('Get                                     WaterDetectorStateResult', 'OK'), ('ModuleID', '1'), ('IsWater', 'false')])
dlink.py:296: RuntimeWarning: coroutine 'ClientSession.close' was never awaited
  session.close()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x75bb5670>
ERROR:asyncio:Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x75baae30>, 65                                     10.62535439)]']
connector: <aiohttp.connector.TCPConnector object at 0x75bb5690>

**Comment by Molodax** [comment]
While the sensor is triggering:

(homeassistant) homeassistant@raspberrypi:~/.homeassistant/custom_components/dlink_hnap $ python3 dlink.py 192.168.149.151 534691 water_detected
DEBUG:asyncio:Using selector: EpollSelector
INFO:__main__:Logging into device
DEBUG:__main__:Challenge: E6FrwGH5xPLsiVJGhq3C, Public key: 8vFdA2db5jPYCiunMOw1, Cookie: X3uVQEmRer
DEBUG:__main__:Private key: 1A242BB1F909773E02DBF79D7B5110B2
DEBUG:__main__:Generated new token for Login: 6C7435A710B1DF8A3C0B8B9DE6353195 (time: 1595801008)
DEBUG:__main__:Generated new token for GetDeviceSettings: FB4CAF828B2AB62FD622A50DDE1A4E92 (time: 1595801008)
DEBUG:__main__:Generated new token for GetModuleSOAPActions: 697682583B6F20CCB846D1304E38F415 (time: 1595801008)
DEBUG:__main__:Generated new token for GetWaterDetectorState: 1FC2C5DA643D35970129001E459A62B4 (time: 1595801008)
Water detectes: OrderedDict([('@xmlns', 'http://purenetworks.com/HNAP1/'), ('GetWaterDetectorStateResult', 'OK'), ('ModuleID', '1'), ('IsWater', 'true')])
dlink.py:296: RuntimeWarning: coroutine 'ClientSession.close' was never awaited
  session.close()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x75b0b690>
ERROR:asyncio:Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x75b00e68>, 6690.899479988)]']
connector: <aiohttp.connector.TCPConnector object at 0x75b0b6b0>

**Comment by postlund** [comment]
Ah, yes, this look good! Exactly what I needed to confirm. I'll try to get going tonight. Thanks a lot!

**Comment by postlund** [comment]
Maybe I can ask for one more thing? I would like to expose the firmware version as well as that can help with troubleshooting in the future. I think it's part of `GetDeviceSettings`. So could you open dlink.py, replace `GetWaterDetectorState` with `GetDeviceSettings` and run the script again in the exact same way?

**Comment by Molodax** [comment]
> Maybe I can ask for one more thing? I would like to expose the firmware version as well as that can help with troubleshooting in the future. I think it's part of `GetDeviceSettings`. So could you open dlink.py, replace `GetWaterDetectorState` with `GetDeviceSettings` and run the script again in the exact same way?

I've made the changes and run the same command, though, not sure if there is any difference in the response:

DEBUG:asyncio:Using selector: EpollSelector
INFO:__main__:Logging into device
DEBUG:__main__:Challenge: nfVrIPBqed2YNTnMn87S, Public key: D1P6EWlxS4i7IMDXn2Zn, Cookie: oRJXaEbXVS
DEBUG:__main__:Private key: 900BC1732B6B7CE825AEC052EFCFA978
DEBUG:__main__:Generated new token for Login: 0A6DA68D52574BCF8DB7C97E1C120EDF (time: 1595875321)
DEBUG:__main__:Generated new token for GetDeviceSettings: 28F2102D668D2797D3213382890732F8 (time: 1595875321)
DEBUG:__main__:Generated new token for GetModuleSOAPActions: B1BFFFF90BF00A863395BE808FF0C72D (time: 1595875322)
DEBUG:__main__:Generated new token for GetWaterDetectorState: 6D376D3DDAE1B677E2AB4BE6C630F435 (time: 1595875322)
Water detectes: OrderedDict([('@xmlns', 'http://purenetworks.com/HNAP1/'), ('GetWaterDetectorStateResult', 'OK'), ('ModuleID', '1'), ('IsWater', 'false')])
dlink.py:296: RuntimeWarning: coroutine 'ClientSession.close' was never awaited
  session.close()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x75b696b0>
ERROR:asyncio:Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x75b5edf8>, 81004.49924135)]']
connector: <aiohttp.connector.TCPConnector object at 0x75b696d0>

**Comment by postlund** [comment]
Hmm, no, it looks like it's the old command. Can you double verify the change in the file?

**Comment by Molodax** [comment]
> Hmm, no, it looks like it's the old command. Can you double verify the change in the file?

line 208:
`resp = await self.client.call("GetDeviceSettings", ModuleID=self.module_id)`

there cannot be any cache, right?

**Comment by Molodax** [comment]
sorry, wait a minute, I've mixed up homeassistant versions....

**Comment by Molodax** [comment]
the correct one:

DEBUG:asyncio:Using selector: EpollSelector
INFO:__main__:Logging into device
DEBUG:__main__:Challenge: NzinRfgQ09uHRzSkYeOR, Public key: eIdrjXulB14teEZWH9IB, Cookie: 9IVgjDvnZc
DEBUG:__main__:Private key: 29668AC47A52D6DC39045F00E8CDDD00
DEBUG:__main__:Generated new token for Login: CADC55C90714C967292EA7A1274A057F (time: 1595877860)
DEBUG:__main__:Generated new token for GetDeviceSettings: 8AAE08A0E36339CF165BE3C45ACFE557 (time: 1595877860)
DEBUG:__main__:Generated new token for GetModuleSOAPActions: 8F48EEBD6A6E693AC94DCBB04F1ADE23 (time: 1595877860)
DEBUG:__main__:Generated new token for GetDeviceSettings: 8AAE08A0E36339CF165BE3C45ACFE557 (time: 1595877860)
Water detectes: OrderedDict([('@xmlns', 'http://purenetworks.com/HNAP1/'), ('GetDeviceSettingsResult', 'OK'), ('Type', 'ConnectedHomeClient'), ('DeviceName', 'Water sensor'), ('VendorName', 'D-Link'), ('ModelDescription', 'D-Link Water Detector'), ('ModelName', 'DCH-S160'), ('DeviceMacId', 'E5:6F:13:E9:78:AC'), ('FirmwareVersion', '1.23'), ('FirmwareRegion', 'Default'), ('LatestFirmwareVersion', '1.23'), ('HardwareVersion', 'A2'), ('HNAPVersion', '0124'), ('PresentationURL', 'http://dch.local'), ('CAPTCHA', 'false'), ('ModuleTypes', OrderedDict([('string', 'Environmental Sensor')])), ('SOAPActions', OrderedDict([('string', ['http://purenetworks.com/HNAP1/Reboot', 'http://purenetworks.com/HNAP1/SetFactoryDefault', 'http://purenetworks.com/HNAP1/IsDeviceReady', 'http://purenetworks.com/HNAP1/GetDeviceSettings', 'http://purenetworks.com/HNAP1/SetDeviceSettings', 'http://purenetworks.com/HNAP1/GetDeviceSettings2', 'http://purenetworks.com/HNAP1/SetDeviceSettings2', 'http://purenetworks.com/HNAP1/GetGroupSettings', 'http://purenetworks.com/HNAP1/SetGroupSettings', 'http://purenetworks.com/HNAP1/GetSystemLogs', 'http://purenetworks.com/HNAP1/CleanSystemLogs', 'http://purenetworks.com/HNAP1/GetModuleSchedule', 'http://purenetworks.com/HNAP1/SetModuleSchedule', 'http://purenetworks.com/HNAP1/GetModuleEnabled', 'http://purenetworks.com/HNAP1/SetModuleEnabled', 'http://purenetworks.com/HNAP1/GetModuleProfile', 'http://purenetworks.com/HNAP1/SetModuleProfile', 'http://purenetworks.com/HNAP1/GetModuleSOAPActions', 'http://purenetworks.com/HNAP1/GetTimeSettings', 'http://purenetworks.com/HNAP1/SetTimeSettings', 'http://purenetworks.com/HNAP1/GetModuleGroup', 'http://purenetworks.com/HNAP1/SetModuleGroup', 'http://purenetworks.com/HNAP1/GetScheduleSettings', 'http://purenetworks.com/HNAP1/SetScheduleSettings', 'http://purenetworks.com/HNAP1/GetRecursiveSchedule', 'http://purenetworks.com/HNAP1/SetRecursiveSchedule', 'http://purenetworks.com/HNAP1/GetFirmwareStatus', 'http://purenetworks.com/HNAP1/GetFirmwareValidation', 'http://purenetworks.com/HNAP1/StartFirmwareDownload', 'http://purenetworks.com/HNAP1/PollingFirmwareDownload', 'http://purenetworks.com/HNAP1/CheckNewFirmware', 'http://purenetworks.com/HNAP1/SettriggerADIC', 'http://purenetworks.com/HNAP1/GetInternetSettings', 'http://purenetworks.com/HNAP1/GetCurrentInternetStatus', 'http://purenetworks.com/HNAP1/GetWLanRadios', 'http://purenetworks.com/HNAP1/SetTriggerWirelessSiteSurvey', 'http://purenetworks.com/HNAP1/GetSiteSurvey', 'http://purenetworks.com/HNAP1/SetAPClientSettings', 'http://purenetworks.com/HNAP1/GetAPClientSettings'])])), ('SubDeviceURLs', None)])
dlink.py:296: RuntimeWarning: coroutine 'ClientSession.close' was never awaited
  session.close()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x75b6a6d0>
ERROR:asyncio:Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x75b5fdf8>, 83542.9520077)]']
connector: <aiohttp.connector.TCPConnector object at 0x75b6a6f0>

**Comment by Molodax** [comment]
very minor: the water sensor has still a motion sensor icon

**Comment by postlund** [comment]
That is perfect, thanks! 😀

The icon and all that will be fixed (the class is wrong). Will push an update within an hour.

**Comment by postlund** [comment]
I have pushed an update to this PR now, supporting both S150 and S160. Notice that you have to specify `type` as `motion` or `water` depending on sensor type. Please give it a spin and let me know if it works!

**Comment by Molodax** [comment]
> I have pushed an update to this PR now, supporting both S150 and S160. Notice that you have to specify `type` as `motion` or `water` depending on sensor type. Please give it a spin and let me know if it works!

It works perfectly fine, thank you!

P.S. just a question whether `timeout` would be a valid parameter (make any difference) for water sensor or it is only for motion sensor? I didn't specify it so the water sensor was 'on' as long as the device was signalling on the water detection and turned off immediately after water was removed, i.e. less than the default 35 s mentioned as the default setting.

**Comment by ebear5** [comment]
Confirmed that it works perfectly.  Thank you!

**Comment by postlund** [comment]
That sound just great 😊 The timeout is only for the motion sensor as you guessed, really no way for me to remove it since both sensor types are binary sensors. But I will add a note about it.

**Comment by postlund** [comment]
Just pushed #8 with support for device_info and unique_id, which I'm a little bit more uncertain about. If you guys have some time to verify it, that would be appreciated!

**Comment by neostim** [comment]
Is this integration still working? I've got an S161 water leak detector but it has no open ports when I scan it, I power cycled it and can see the matching MAC address and IP (just to confirm), but when I try connecting using this integration I get:

aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.0.34:80 ssl:default [Connect call failed ('192.168.0.34', 80)]

and like I said, port scans show nothing open, trying to connect directly via web page doesn't work either.

**Pull request merged**
